@base_url = http://localhost:8080

### Route to save a person
POST {{base_url}}/api/people HTTP/1.1
Content-Type: application/json

{
  "name": "John",
  "lastName": "Doe",
  "birthDate": "2002-10-20",
  "email": "john.doe@person.com"
}

### Route to pick up all the people
GET {{base_url}}/api/people HTTP/2
Content-Type: application/json

### Route to pick up all the people with filter age range
GET {{base_url}}/api/people?ageStart=19&ageEnd=29 HTTP/2
Content-Type: application/json

### Route to update a person by id
PUT {{base_url}}/api/people/{{id}} HTTP/1.1
Content-Type: application/json

{
  "name": "John",
  "lastName": "Doe",
  "birthDate": "2002-12-20",
  "email": "teu_cu@gmail.com"
}

### Route to find a person by id
GET {{base_url}}/api/people/{{id}}} HTTP/2
Content-Type: application/json

### Route to delete a person by id
DELETE {{base_url}}/api/people/{{id}}} HTTP/2
Content-Type: application/json